フッターの追加
Server-Starter-for-Minecraft/Server-Starter-for-Minecraft.github.io pull request #15
Opened 2024-04-15 15:18 UTC by CivilTT

# フッターの追加

ホームページ最下部にフッターを追加した
常に一番下に描画される仕様とし，スクロール状況に応じて表示非表示が切り替わることはない

## UI案からの変更点
- フッター内のリンクはボタンで表示する形式とし，ヘッダーのようにテキストでは表示しない
    - テキスト表示の場合，領域幅が大きくなりすぎるため，モバイル対応を考えたときに配置を綺麗に見せることが難しい
- 右下のテキストは「All Rights Reserved」に変更
    - 更新日時の表示はあまり意味がないため，一般的に表示されている権利関係のテキストに修正
- リンクボタンと右下のテキストは２段に分割
    - 両者を１段に記述する場合，モバイル対応時の配置が困難になるため

2024-04-20 13:37 UTC, txkodo reviewed
利権関係のコメントが書いてあるのはとても納得感あってよいと思います。

アイコンだけだと何のボタンなのかわからない印象を受けます。
整理すると以下2点が気になりました。

1. GitHubはOKとして、問い合わせとサイトマップは一般的に意味が伝わるアイコンではない
2. GitHubとXは外部サービスが開くのに対して、サイトマップは内部でのページ遷移になっており、アクションの種別が異なる

やはり説明の文字が欲しいのと、
異なる種別のアクションの並列を解消したいです。

後者に関しては元デザインにも問題があるように思います。

モバイルビューでフッターが複数行にわたるデザインは、よく見ると思うので
モバイルの時は左寄せで複数行にしてしまうのがいいかもしれません。

詳しいデザインに関してはまた相談しましょう。

2024-04-27 13:10 UTC, txkodo requested changes
サイトマップ自体の必要性自体が現状あまりないと思うので、
フッターはGitHubとXのアイコンを並べる対応としましょう。

2024-04-28 15:53 UTC, CivilTT commented
@txkodo 

フッターにおけるアイコンの整理とサイトマップページの削除を行いました
Tooltipについては破壊的な変更（引数の削除とslotの追加）を行っていますが，利用規約に関する変更に際して行った内容と同一の変更としているため，衝突の危険性はありません

2024-05-04 14:07 UTC, txkodo approved these changes
確認しました！

2024-05-04 14:07 UTC, merged