Create home page
Server-Starter-for-Minecraft/Server-Starter-for-Minecraft.github.io pull request #17
Opened 2024-04-19 13:29 UTC by nozz-mat

# トップページを作成

## 変更箇所

- UI案に従いトップページを実装しました
- 各項目ごとにsrc/components/pages/HOME以下にコンポーネントを実装し、それを用いて実装しています。
## 承認者への申し送り事項

- src/components/Pages/HOME/ServerCard.vueに関して
  - カード生成部分の実装に関して、現在はdesignページのcolorThemesを参考にしていますが綺麗な実装に直したいです
  - カードの体裁が崩れる問題が残っています
- 埋め込まれているリンク先に関して
  - リンクが設定できる場所(SsA,SsRouterBtn,SsLinkBtn)は基本的に仮でリンクを設定しています。意図するリンクに変えて頂きたいです。
- 画像に関しても仮置きです。デザイン案のものそのままでよければ画像をいただければ置き換えます。

2024-04-21 12:01 UTC, CivilTT requested changes
UI上の修正点と実装思想上の修正点をレビューしています

- コードそれぞれの具体的なレビューはコード内のコメント
- 全体的な変更点は下記に列挙

しているため，両者あわせて確認してください

## 全体的な修正点
- 仮の要素（画像やリンクなど）がある状態は「作業が終わった」とは言えません
Draftの状態なら問題ないですが，Openの状態するときには「作業が終わった」状態にしてください（画像やリンクが不足している場合は実装者が用意してください）
（どうしても何か特別な理由があって仮の状態を残す場合は当該Issuesを立てる等，要変更箇所が分かるようにしてください）
- ファイル名の命名規則とそれらの格納場所は下記の通りのため，反映してください
    - `○○Page.vue`：画面を読み込むときに一番最初に読み込まれるファイル（`/pages`直下，親子関係のページは同様の命名規則で`/pages/(ページ名)/`の中に格納）
    - `○○View.vue`：`Page`から直接呼び出すコンポーネント（`/components/Pages/(ページ名)/`の中に格納）
    - （`View`から呼び出すコンポーネント）：２単語以上で構成されたファイル名（`/components/Pages/(ページ名)/core/`の中に格納）
    - （汎用的に呼び出すコンポーネント）：２単語以上で構成されたファイル名（`/components/utils/(base | baseDialog)/`の中に格納）
- `assets`フォルダ内の構造規則は下記のとおりです
    - (`Page`の名前)/(`View`の名前)/：`Page`内で使用する`View`が利用するassetsを格納
    - `その他`：「OS」や「Ngrok」のように特定のグループとして汎用的に利用可能な画像は直接フォルダを作成してその中に格納

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/PortMappingView.vue
> +<template>
divを外側にかけてブロックとしてまとめる
ImgTxtBlockを使っていない`View`は`<div class="q-pr-md">`として，右側に`md`サイズのMarginを入れる

※コメントが入っていない要素やHOMEの中で同様の誤りがある箇所はすべて修正

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ServerCard.vue
> +
以下のようなリストは下記のリンクのようにi18nと組み合わせて表現してください
https://github.com/Server-Starter-for-Minecraft/Server-Starter-for-Minecraft.github.io/blob/AddTerms/src/components/Pages/Terms/TermsList.vue

この時に，本体実装側でIssuesとして出されているエラーが発生しないようにする
（特に改行を入れる際などに`v-html`を使わないようにする）
https://github.com/Server-Starter-for-Minecraft/ServerStarter2/issues/138

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ImageBlock.vue
> +<script setup lang="ts">
`GrandUpdate-v2.2.0`ブランチに`ImgTxtBlock`という名前のコンポーネントを`ImageBlock`と同様の実装で新設していますので，これをマージして，`ImageBlock`を`ImgTxtBlock`に置き換えてください

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ServerCard.vue
> +    desc: 'Minecraftの公式サーバー.標準的なマルチプレイの機能を提供する.',
- 「，」「．」「！」などの記号は全角に統一
- 「．」の後は改行を入れることで，文章の途中で改行されないようにする
- タイトルの「○○サーバー」の「サーバー」は削除（例：Forgeサーバー → Forge）

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ServerCard.vue
> +                  :path="imgPath(server.name)"
関数にせず，
```
:path="`/assets/servers/${server.name}/.png`"
```
で埋め込んでください

また，文字列内に変数を埋め込むときには「＋」でつなぐのではなく，上記の記法を標準で使用してください

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ServerCard.vue
> +      >を使って,もっとマルチプレイを楽しみましょう.
文中にタグを埋め込む場合は下記のように表現し，「>」などタグの一部がどこかに飛び出さないように記載してください

```html
<p>
  ServerStarterは6種類のサーバーに対応しています!<br />
  バニラのサーバーだけでなく
  <SsA url="/intro">Mod</SsA>や
  <SsA url="/intro">プラグイン</SsA>
  を使って,もっとマルチプレイを楽しみましょう.
</p>
```

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/PortMappingView.vue
> +  </p>
文中にタグを埋め込む場合は下記のように表現し，「>」などタグの一部がどこかに飛び出さないように記載してください

※以下，同様の箇所についてはコメントがなくても修正

```html
<p>
  Ngrok
  <SsLinkBtn
    url="https://ngrok.com"
  />
  に無料で登録して，面倒な設定をすべてスキップしましょう！
</p>
```

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/ServerCard.vue
> +    </p>
カードの実装を最下部のように変更してください
修正のポイントは下記のとおりです．

- カード同士や要素同士の隙間は`gutter`(q-gutter-lg，q-gutter-x-md)で調整
- カードの幅は「画面が大きい場合は30rem，小さい場合は画面幅の90%」を実現するために`min(30rem,90vw)`を追加
- カードの最大幅が固定値のため，左右に余白ができた際のスタイルとして`justifty-center`を追加
- カード内の要素はカードの中央（高さ方向）に表示させるため，`flex items-center`を追加
- `blockWidth`クラスに対応する`<style>`の定義がないため削除
- 画像幅は`4rem`に固定（普通に幅を指定するときには`width`を使う）
- テキスト要素（説明文等）には`<p>`を使うが，ピンポイントで指定する独自のスタイルを適用させる短いテキストには`<span>`を使う
- 基本的に`col-auto`は使わない（`col-auto`を使おうとしているブロック以外のブロックで`col`を使って幅を指定していけば，残ったブロックは自動的に幅が調整される）
- 無駄にdivでくくらない（ネストは極力浅くなるようにする）
- （styleプロパティが長くなってきているため，`<style>`を作成し，スタイル設定を整理しても良い）


```html
    <div class="row q-gutter-lg justify-center">
      <template v-for="server in ServerTypes()" :key="server.name">
        <SsCard class="flex items-center" style="width: min(30rem, 90vw)">
          <div class="row q-gutter-x-md items-center">
            <q-img
              :src="`/assets/servers/${server.name}.png`"
              style="width: 4rem "
            />
            <div class="col">
              <span style="font-size: 1.5em; font-family: 'Genokaku JP'">
                {{ server.display }}
                <SsLinkBtn :url="server.url" />
              </span>
              <p class="q-mt-md">{{ server.desc }}</p>
            </div>
          </div>
        </SsCard>
      </template>
    </div>
    <div class="flex justify-end q-py-md">
      <SsRouterBtn :to="btnTo">
        {{ btnTitle }}
      </SsRouterBtn>
    </div>
```

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/SummaryView.vue
> +    <ssSubTitle> ServerStarterでマルチプレイを始めましょう !! </ssSubTitle>
SsTitleを使う

2024-04-21 12:01 UTC, CivilTT commented on src/components/Pages/HOME/SummaryView.vue
> +    <div class="flex justify-center">
`q-py-md`を追加し，ボタンとテキストの余白を確保する

2024-04-21 12:01 UTC, CivilTT commented on src/pages/HomePage.vue
>        <ProductIntro />
今回の設計思想は，「`Page`内は単純なコンポーネントを並べるだけとし，詳細な実装はその下部構造で実装する」としているため，`Page`中身に細かい実装は書きません

従って，32行目以降のような詳細な実装はここには書かず，`MultiplayView.vue`のようなコンポーネントを新設し，その中に`<ImageBlock>`以下の実装を記入するようにしてください

2024-04-21 12:01 UTC, CivilTT commented on src/pages/HomePage.vue
> +      <ServerCard btnTitle="サーバーの種類" btnTo="/intro" />
ここで引数を取る必要はないので，削除してください
「全体的な修正」で入れているようにコンポーネントの名前も修正してください

2024-04-21 12:01 UTC, CivilTT commented on src/pages/HomePage.vue
>        <!-- HOMEのコンテンツを記述 -->
上記のコメントは意図を伝えるためだけの内容のため，削除してください

2024-04-21 12:01 UTC, CivilTT commented on src/pages/HomePage.vue
> +      <PortMappingView />
`<PortMappingView>`という名前を見れば「ポート開放」の記事であることは一目瞭然のためコメントを削除してください
一般的に一目でわかる内容にコメントは入れません

※このほかのViewを呼び出している箇所につけているコメントも同様に不要

2024-04-27 14:05 UTC, nozz-mat commented
画像に関して
- １つ下のコンポーネントの要素とかぶる
- ウインドウサイズを調整すると一部横が見切れる
という問題があります

2024-04-28 10:20 UTC, CivilTT approved these changes
@nozz-mat 

`ImgTxtBlock`の修正が完了したため，このブランチにMargeしました

このほかに，指摘事項に対して再度レビューを行いましたが，指摘事項が修正されていない箇所が散見されたため，こちらで修正しました
修正点の概要は下記に示しますが，指摘事項が直っていないのは成果物としての品質が低いと感じるので，気を付けてください

## 修正点概要（重大）
- 仮の値の修正が終わっていない（＝各サーバーのリンク，「使い方を詳しく」のような内部リンクが当てられていない）

## 修正点概要（軽微）
- コンポーネント名の命名規則違反が修正されていない
- 変数の命名規則違反を修正（一般的にローカル変数の１文字目は小文字）
- `assets`の画像ファイルの命名規則違反を修正（コンポーネントを除く一般的なファイル名の１文字目は小文字）
- ImgTxtBlockを「使っていない」Viewに`q-pr-md`を付ける必要があると記載しているにもかかわらず，ImgTxtBlockの外側にdivを入れて`q-pr-md`を付けている箇所がある（`q-pr-md`を入れる仕様は統一性がない仕様であったため，廃止とするように修正しました）
- 「>」のようなタグの一部が飛び出している現象が`ProductIntroView.vue`, `SummaryView.vue`でも発生していた
- `ServerView.vue`（旧`ServerCard.vue`）にあった`{{ 'サーバーの種類' }}`について，定数を記述するときに`{{ '' }}`は不要

2024-04-28 10:21 UTC, merged

2024-04-28 16:03 UTC, CivilTT commented
@nozz-mat 

`ImgTxtBlock`の修正が完了したため，このブランチにMargeしました

このほかに，指摘事項に対して再度レビューを行いましたが，指摘事項が修正されていない箇所が散見されたため，こちらで修正しました
修正点の概要は下記に示しますが，指摘事項が直っていないのは成果物としての品質が低いと感じるので，気を付けてください

## 修正点概要（重大）
- 仮の値の修正が終わっていない（＝各サーバーのリンク，「使い方を詳しく」のような内部リンクが当てられていない）

## 修正点概要（軽微）
- コンポーネント名の命名規則違反が修正されていない
- 変数の命名規則違反を修正（一般的にローカル変数の１文字目は小文字）
- `assets`の画像ファイルの命名規則違反を修正（コンポーネントを除く一般的なファイル名の１文字目は小文字）
- ImgTxtBlockを「使っていない」Viewに`q-pr-md`を付ける必要があると記載しているにもかかわらず，ImgTxtBlockの外側にdivを入れて`q-pr-md`を付けている箇所がある（`q-pr-md`を入れる仕様は統一性がない仕様であったため，廃止とするように修正しました）
- 「>」のようなタグの一部が飛び出している現象が`ProductIntroView.vue`, `SummaryView.vue`でも発生していた
- `ServerView.vue`（旧`ServerCard.vue`）にあった`{{ 'サーバーの種類' }}`について，定数を記述するときに`{{ '' }}`は不要